### ISSUE TITLE
BE BUG: https://rhapp-backend.rhdevs.repl.co/social/posts DELETE function returns wrong message

### ISSUE THREAD

**Issue by leonghuenweng** [rhdevs/rhapp#561]
When sending a DELETE request to a post that has already been deleted, this function returns a "success" message instead of a "post no longer exist" message

**Comment by ttheng3810** [comment]
Sorry but I need more clarification on this bug: what do you mean by "returning ```success``` message when it should be ```post no longer exist```"?

Do you mean that the wording of the response message is inappropriate, e.g. when a client sends DELETE request to **delete a post that actually exists in the database before the deletion**, returning a ```success``` message instead of ```post no longer exist``` message will confuse the client?

Or is it that the ```success``` response message is not correct and it should be ```post no longer exist```, **if a client requests to delete a post that does not exist in the first place even before the request is sent**?
