### ISSUE TITLE
BE BUG: https://rhapp-backend-devel.rhdevs.repl.co/social/posts PUT function returns error message

### ISSUE THREAD

**Issue by leonghuenweng** [rhdevs/rhapp#616]
request (a valid postID):
{
    "postID":"6218d1affacab7c699f1fa29",
    "description":"haha"
}

response:
{
    "err": "An error has occured",
    "status": "failed"
}

**Comment by ttheng3810** [comment]
My attempt to reproduce this bug does return an error message, but it is a caught ```Post does not exist``` ```404``` error exception, instead of a general ```500``` error message.

![postman screenshot](https://user-images.githubusercontent.com/81245678/156124994-fdc38b57-848e-4638-930f-e92c7d05fab1.png)

This ```404``` error is thrown because of this code snippet.

![404 code snippet](https://user-images.githubusercontent.com/81245678/156125077-461f51d4-b904-4b4d-97ed-0a56cce1dfc2.png)

An error is thrown even though the given ```postID``` is valid because a post with that ```postID``` does not exist in the database, thus a ```404``` error will be thrown, so this does not really seem like a 'bug' to me.

[Or maybe the bug has been fixed before.]

**Comment by leonghuenweng** [comment]
hi!

Thanks for sending the screenshot, I realised the bug only exists in the development URL shown below, I will ask Nobel about the next course of action and update you again 🙂
https://rhapp-backend-devel.rhdevs.repl.co
________________________________

**Comment by angnobel** [comment]
Right sorry i have fixed this already
